#include "gpio.h"
#include <stm32f411xe.h>

void gpio_init(void) {
  RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN |
                  RCC_AHB1ENR_GPIOCEN | RCC_AHB1ENR_GPIODEN;
  GPIOA->MODER &= ~(GPIO_MODER_MODE2 | GPIO_MODER_MODE4 | GPIO_MODER_MODE11 |
                    GPIO_MODER_MODE12);
  GPIOA->MODER |= GPIO_MODER_MODE2_1 | GPIO_MODER_MODE4_1 |
                  GPIO_MODER_MODE11_1 | GPIO_MODER_MODE12_1;
  GPIOA->AFR[0] |= 7 << GPIO_AFRL_AFSEL2_Pos;
  GPIOA->AFR[0] |= 6 << GPIO_AFRL_AFSEL4_Pos;

  GPIOA->AFR[1] |=
      (10 << GPIO_AFRH_AFSEL11_Pos) | (10 << GPIO_AFRH_AFSEL12_Pos);

  GPIOB->MODER &= ~(GPIO_MODER_MODE6 | GPIO_MODER_MODE9);
  GPIOB->MODER |= GPIO_MODER_MODE6_1 | GPIO_MODER_MODE9_1;
  GPIOB->AFR[0] |= 4 << GPIO_AFRL_AFSEL6_Pos;
  GPIOB->AFR[1] |= 4 << GPIO_AFRH_AFSEL9_Pos;
  GPIOB->PUPDR |= GPIO_PUPDR_PUPDR6_0 | GPIO_PUPDR_PUPDR9_0;
  GPIOB->OTYPER |= GPIO_OTYPER_OT6 | GPIO_OTYPER_OT9;

  GPIOC->MODER &= ~(GPIO_MODER_MODE7 | GPIO_MODER_MODE10 | GPIO_MODER_MODE12);
  GPIOC->MODER |=
      GPIO_MODER_MODE7_1 | GPIO_MODER_MODE10_1 | GPIO_MODER_MODE12_1;
  GPIOC->AFR[0] |= 6 << GPIO_AFRL_AFSEL7_Pos;
  GPIOC->AFR[1] |= (6 << GPIO_AFRH_AFSEL10_Pos) | (6 << GPIO_AFRH_AFSEL12_Pos);
  GPIOC->OSPEEDR |=
      GPIO_OSPEEDR_OSPEED7 | GPIO_OSPEEDR_OSPEED10 | GPIO_OSPEEDR_OSPEED12;

  GPIOD->MODER &= ~(GPIO_MODER_MODE4 | GPIO_MODER_MODE15);
  GPIOD->MODER |= GPIO_MODER_MODE4_0 | GPIO_MODER_MODE15_0;
}
