#include "gpio.h"
#include <stm32f411xe.h>

void gpio_init(void) {
  RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIODEN;
  GPIOA->MODER &= ~(GPIO_MODER_MODE2 | GPIO_MODER_MODE11 | GPIO_MODER_MODE12);
  GPIOA->MODER |=
      GPIO_MODER_MODE2_1 | GPIO_MODER_MODE11_1 | GPIO_MODER_MODE12_1;
  GPIOA->AFR[0] |= 7 << GPIO_AFRL_AFSEL2_Pos;
  GPIOA->AFR[1] |=
      (10 << GPIO_AFRH_AFSEL11_Pos) | (10 << GPIO_AFRH_AFSEL12_Pos);

  GPIOD->MODER &= ~GPIO_MODER_MODE15;
  GPIOD->MODER |= GPIO_MODER_MODE15_0;
}
